module.exports = {
  'FACEBOOK' : 'Facebook',
  'SLACK' : 'Slack',
  'TWILIO' : 'Twilio',
  'NEXMO' : 'Nexmo',
  'NOPE' : 'Nope',
  'WIT_AI' : 'Wit.ai',
  'API_AI' : 'Api.ai',
  'RECAST_AI' : 'Recast.ai',
  'WATSON' : 'Watson',
  'LUIS' : 'Luis',
  'NO_ONE' : 'No one',
  'MONGODB' : 'MongoDB',
  'REDISDB' : 'RedisDB',
  'COUCHDB' : 'CouchDB',
  'DATASTORE' : 'Datastore',
  'FIREBASE' : 'Firebase',
  'POSTGRESQL' : 'Postgres',
  'NPM' : 'Npm',
  'YARN' : 'Yarn',
  'ES6' : 'ES6',
  'ECMASCRIPT_5' : 'ECMASCRIPT 5'
};
