module.exports = {
  'FACEBOOK' : 'Facebook',
  'SLACK' : 'Slack',
  'CISCO' : 'Cisco',
  'NOPE' : 'Nope',
  'WIT_AI' : 'Wit.ai',
  'API_AI' : 'Api.ai',
  'RECAST_AI' : 'Recast.ai',
  'WATSON' : 'Watson',
  'LUIS' : 'Luis',
  'NO_ONE' : 'No one',
  'MONGODB' : 'MongoDB',
  'REDISDB' : 'RedisDB',
  'COUCHDB' : 'CouchDB',
  'DATASTORE' : 'Datastore',
  'FIREBASE' : 'Firebase',
  'POSTGRESQL' : 'Postgres',
  'YES' : 'Yes',
  'NO' : 'No',
  'ES6' : 'ES6'
};
